export const productsDatas = [
    {
        id: "1",
        Name: "Coca Cola",
        Category: "Drinks",
        UnderCategory: "",
        Picture: "https://toulouse2.coexo.fr/3756-large_default/coca-cola-canette-33cl-unite-33-cl-.jpg",
        Description: "Coca bien frais chacal",
        Price: "1",
        FullPrice: "1.20",
        
    },
    {
        id: "2",
        Name: "Fanta Citron",
        Category: "Drinks",
        UnderCategory: " ",
        Picture: "https://www.resto-sushis.com/media/catalog/product/cache/100f1fc6c4ef37a43645b86596640859/f/a/fanta_citron.png",
        Description: "Fanta bien frais, citron chacal !",
        Price: "1",
        FullPrice: "1.20",
    },
    {
        id: "3",
        Name: "Fanta Orange",
        Category: "Drinks",
        UnderCategory: " ",
        Picture: "https://lejardindelorient.restaur-app.fr/medias/picts/boutique/2000x2000/ecf9a549-12fa-4a79-bd09-c2f9f993cb24-9pez.png",
        Description: "Fanta bien frais, orange chacal !",
        Price: "1",
        FullPrice: "1.20",
    },
    {
        id: "4",
        Name: "Riz Jasmin",
        Category: "Base",
        UnderCategory: "Riz",
        Picture: "",
        Description: "Riz blanc, légèrement aromatisé au jasmin.",
        Price: "",
        FullPrice: "",
    },
    {
        id: "5",
        Name: "Riz complet",
        Category: "Base",
        UnderCategory: "Riz",
        Picture: "",
        Description: "",
        Price: "",
        FullPrice: "",
    },
    {
        id: "6",
        Name: "Nouille Udon",
        Category: "Base",
        UnderCategory: "Nouilles",
        Picture: "",
        Description: "",
        Price: "",
        FullPrice: "",
    },
    {
        id: "7",
        Name: "Nouille de Riz",
        Category: "Base",
        UnderCategory: "Nouilles",
        Picture: "",
        Description: "",
        Price: "",
        FullPrice: "",
    },
    {
        id: "8",
        Name: "Boeuf",
        Category: "Viandes",
        UnderCategory: "",
        Picture: "",
        Description: "Boeuf Halal de 1ère qualité.",
        Price: "2",
        FullPrice: "2.40",
    },
    {
        id: "9",
        Name: "Crevette",
        Category: "Viandes",
        UnderCategory: "",
        Picture: "",
        Description: "",
        Price: "2",
        FullPrice: "2.40",
    },
    {
        id: "10",
        Name: "Shitake",
        Category: "Légumes",
        UnderCategory: "",
        Picture: "",
        Description: "",
        Price: "1",
        FullPrice: "1.20",
    },
    {
        id: "11",
        Name: "Ananas",
        Category: "Légumes",
        UnderCategory: "",
        Picture: "",
        Description: "",
        Price: "0.50",
        FullPrice: "0.60",
    },
    {
        id: "12",
        Name: "Pakchoi",
        Category: "Légumes",
        UnderCategory: "",
        Picture: "",
        Description: "",
        Price: "0.48",
        FullPrice: "0.60",
    },
    {
        id: "13",
        Name: "Oignons rouges",
        Category: "Légumes",
        UnderCategory: "",
        Picture: "",
        Description: "",
        Price: "0.5",
        FullPrice: "0.6",
    },
    {
        id: "14",
        Name: "Spicy",
        Category: "Sauce",
        UnderCategory: "",
        Picture: "",
        Description: "",
        Price: "",
        FullPrice: "",
    },
    {
        id: "15",
        Name: "Miel",
        Category: "Sauce",
        UnderCategory: "",
        Picture: "",
        Description: "",
        Price: "",
        FullPrice: "",
    },
    {
        id: "16",
        Name: "Cacahuetes",
        Category: "Petit+",
        UnderCategory: "",
        Picture: "",
        Description: "",
        Price: "",
        FullPrice: "",
    },
    {
        id: "17",
        Name: "Coriandre",
        Category: "Petit+",
        UnderCategory: "",
        Picture: "",
        Description: "",
        Price: "",
        FullPrice: "",
    },
    {
        id: "18",
        Name: "Riz Gluant Mangue",
        Category: "Dessert",
        UnderCategory: "",
        Picture: "https://static.vecteezy.com/system/resources/previews/026/757/837/non_2x/mango-sticky-rice-with-ai-generated-free-png.png",
        Description: "",
        Price: "2.80",
        FullPrice: "3.50",
    },
    {
        id: "19",
        Name: "Tiramitsu Fraise",
        Category: "Dessert",
        UnderCategory: "Tiramitsu",
        Picture: "https://lh3.googleusercontent.com/proxy/dSBshRzTaXwFVavcgsNcDB4kG8t_HQ4p1B63dCA2csPyHVPNoog5kiEXZHncWdSrPZgz9We5RiMlS0G8TkNvJSyqAM0OXK9pe-wyDSqw8kdcxqNJPmglEcwpTnYNlVA5s50bKETbVGeLuMetgacwLQyRKpUCnQluzPi15zQ",
        Description: "",
        Price: "2.80",
        FullPrice: "3.50",
    },
    {
        id: "20",
        Name: "Tiramitsu Nutella",
        Category: "Dessert",
        UnderCategory: "Tiramitsu",
        Picture: "https://www.commande-yumity.fr/wp-content/uploads/2022/04/tira-nutella.png",
        Description: "",
        Price: "2.80",
        FullPrice: "3.50",
    },
    {
        id: "22",
        Name: "Poulet Dynamite",
        Category: "Entrées",
        UnderCategory: "",
        Picture: "https://tb-static.uber.com/prod/image-proc/processed_images/17d00a9f82c8ef242203505f223fec4b/7f4ae9ca0446cbc23e71d8d395a98428.jpeg",
        Description: "",
        Price: "3.20",
        FullPrice: "4",
    },
    {
        id: "23",
        Name: "Nems Poulet",
        Category: "Entrées",
        UnderCategory: "Rouleau",
        Picture: "https://tb-static.uber.com/prod/image-proc/processed_images/a9d9bf5b29c908aeccb89721973c3326/f0d1762b91fd823a1aa9bd0dab5c648d.jpeg",
        Description: "",
        Price: "2.80",
        FullPrice: "3.50",
    },{
        id: "24",
        Name: "Rouleau de Printemps",
        Category: "Entrées",
        UnderCategory: "Rouleau",
        Picture: "https://christinapotvin.com/wp-content/uploads/2021/03/Rouleaux-de-printemps-mix.jpg",
        Description: "",
        Price: "2.80",
        FullPrice: "3.50",
    },
]
