export const productsDatas = [
    {
        id: "55501",
        Name: "Poulet Dynamite",
        Category: "Entrées",
        UnderCategory: "",
        Picture: "55522.jpeg",
        Description: "",
        Price: "3.20",
        FullPrice: "4",
    },
    {
        id: "55502",
        Name: "Nems Poulet",
        Category: "Entrées",
        UnderCategory: "Rouleau",
        Picture: "55523.jpeg",
        Description: "",
        Price: "2.80",
        FullPrice: "3.50",
    },
    {
        id: "55503",
        Name: "Rouleau de Printemps",
        Category: "Entrées",
        UnderCategory: "Rouleau",
        Picture: "55524.jpeg",
        Description: "",
        Price: "2.80",
        FullPrice: "3.50",
    },


    {
        id: "55511",
        Name: "Riz Jasmin",
        Category: "Base",
        UnderCategory: "Riz",
        Picture: "5554.jpeg",
        Description: "Riz blanc, légèrement aromatisé au jasmin.",
        Price: "",
        FullPrice: "",
    },
    {
        id: "55512",
        Name: "Riz complet",
        Category: "Base",
        UnderCategory: "Riz",
        Picture: "5555.jpeg",
        Description: "",
        Price: "",
        FullPrice: "",
    },
    {
        id: "55513",
        Name: "Nouille Udon",
        Category: "Base",
        UnderCategory: "Nouilles",
        Picture: "5556.jpeg",
        Description: "",
        Price: "",
        FullPrice: "",
    },
    {
        id: "55514",
        Name: "Nouille de Riz",
        Category: "Base",
        UnderCategory: "Nouilles",
        Picture: "5557.jpeg",
        Description: "",
        Price: "",
        FullPrice: "",
    },


    {
        id: "55521",
        Name: "Boeuf",
        Category: "Viandes",
        UnderCategory: "",
        Picture: "55521.jpeg",
        Description: "Boeuf Halal de 1ère qualité.",
        Price: "2",
        FullPrice: "2.40",
    },
    {
        id: "55522",
        Name: "Poulet grillé",
        Category: "Viandes",
        UnderCategory: "",
        Picture: "55522.jpeg",
        Description: "Poulet grillé Halal de 1ère qualité.",
        Price: "2",
        FullPrice: "2.40",
    },
    {
        id: "55523",
        Name: "Dinde",
        Category: "Viandes",
        UnderCategory: "",
        Picture: "55523.jpeg",
        Description: "",
        Price: "2",
        FullPrice: "2.40",
    },
    {
        id: "55524",
        Name: "Crevettes",
        Category: "Viandes",
        UnderCategory: "",
        Picture: "55524.jpeg",
        Description: "",
        Price: "2",
        FullPrice: "2.40",
    },
    {
        id: "55525",
        Name: "Calamars",
        Category: "Viandes",
        UnderCategory: "",
        Picture: "55525.jpeg",
        Description: "",
        Price: "2",
        FullPrice: "2.40",
    },


    {
        id: "55531",
        Name: "Oignons rouges",
        Category: "Légumes",
        UnderCategory: "",
        Picture: "55531.jpeg",
        Description: "",
        Price: "0.5",
        FullPrice: "0.6",
    },
    {
        id: "55532",
        Name: "Oignons",
        Category: "Légumes",
        UnderCategory: "",
        Picture: "55532.jpeg",
        Description: "",
        Price: "0.5",
        FullPrice: "0.6",
    },
    {
        id: "55533",
        Name: "Champignons",
        Category: "Légumes",
        UnderCategory: "",
        Picture: "55533.jpeg",
        Description: "",
        Price: "1",
        FullPrice: "1.20",
    },
    {
        id: "55534",
        Name: "Champignons Shitake",
        Category: "Légumes",
        UnderCategory: "",
        Picture: "55534.jpeg",
        Description: "",
        Price: "1",
        FullPrice: "1.20",
    },
    {
        id: "55535",
        Name: "Pakchoi",
        Category: "Légumes",
        UnderCategory: "",
        Picture: "55535.jpeg",
        Description: "",
        Price: "0.48",
        FullPrice: "0.60",
    },
    {
        id: "55536",
        Name: "Courgettes",
        Category: "Légumes",
        UnderCategory: "",
        Picture: "55536.jpeg",
        Description: "",
        Price: "0.48",
        FullPrice: "0.60",
    },
    {
        id: "55537",
        Name: "Brocolis",
        Category: "Légumes",
        UnderCategory: "",
        Picture: "55537.jpeg",
        Description: "",
        Price: "0.48",
        FullPrice: "0.60",
    },
    {
        id: "55538",
        Name: "Petit Pois",
        Category: "Légumes",
        UnderCategory: "",
        Picture: "55538.jpeg",
        Description: "",
        Price: "0.48",
        FullPrice: "0.60",
    },
    {
        id: "55539",
        Name: "Pousses d'Épinards",
        Category: "Légumes",
        UnderCategory: "",
        Picture: "55539.jpeg",
        Description: "",
        Price: "0.48",
        FullPrice: "0.60",
    },
    {
        id: "555310",
        Name: "Ananas",
        Category: "Légumes",
        UnderCategory: "",
        Picture: "555310.jpeg",
        Description: "",
        Price: "0.50",
        FullPrice: "0.60",
    },
    

    {
        id: "55541",
        Name: "Spicy",
        Category: "Sauce",
        UnderCategory: "",
        Picture: "55541.jpeg",
        Description: "",
        Price: "",
        FullPrice: "",
    },
    {
        id: "55542",
        Name: "Miel",
        Category: "Sauce",
        UnderCategory: "",
        Picture: "55542.jpeg",
        Description: "",
        Price: "",
        FullPrice: "",
    },


    {
        id: "55551",
        Name: "Cacahuetes",
        Category: "Petit+",
        UnderCategory: "",
        Picture: "55551.jpeg",
        Description: "",
        Price: "",
        FullPrice: "",
    },
    {
        id: "55552",
        Name: "Coriandre",
        Category: "Petit+",
        UnderCategory: "",
        Picture: "55552.jpeg",
        Description: "",
        Price: "",
        FullPrice: "",
    },

    
    {
        id: "55511",
        Name: "Coca Cola",
        Category: "Drinks",
        UnderCategory: "",
        Picture: "55511.jpeg",
        Description: "Coca bien frais chacal",
        Price: "1",
        FullPrice: "1.20",
        
    },
    {
        id: "55512",
        Name: "Coca Cola Zéro",
        Category: "Drinks",
        UnderCategory: "",
        Picture: "55512.jpeg",
        Description: "Coca bien frais chacal",
        Price: "1",
        FullPrice: "1.20",
        
    },
    {
        id: "55513",
        Name: "Fanta Citron",
        Category: "Drinks",
        UnderCategory: " ",
        Picture: "55513.jpeg",
        Description: "Fanta bien frais, citron chacal !",
        Price: "1",
        FullPrice: "1.20",
    },
    {
        id: "55514",
        Name: "Fanta Orange",
        Category: "Drinks",
        UnderCategory: " ",
        Picture: "55514.jpeg",
        Description: "Fanta bien frais, orange chacal !",
        Price: "1",
        FullPrice: "1.20",
    },
    {
        id: "55515",
        Name: "Sprite",
        Category: "Drinks",
        UnderCategory: " ",
        Picture: "55515.jpeg",
        Description: "Sprite bien frais chacal !",
        Price: "1",
        FullPrice: "1.20",
    },


    {
        id: "55561",
        Name: "Riz Gluant Mangue",
        Category: "Dessert",
        UnderCategory: "",
        Picture: "55561.jpeg",
        Description: "",
        Price: "2.80",
        FullPrice: "3.50",
    },
    {
        id: "55562",
        Name: "Tiramitsu Fraise",
        Category: "Dessert",
        UnderCategory: "Tiramitsu",
        Picture: "55562.jpeg",
        Description: "",
        Price: "2.80",
        FullPrice: "3.50",
    },
    {
        id: "55563",
        Name: "Tiramitsu Kinder Bueno",
        Category: "Dessert",
        UnderCategory: "Tiramitsu",
        Picture: "55520.jpeg",
        Description: "",
        Price: "2.80",
        FullPrice: "3.50",
    },
    {
        id: "55564",
        Name: "Tiramitsu Nutella",
        Category: "Dessert",
        UnderCategory: "Tiramitsu",
        Picture: "55564.jpeg",
        Description: "",
        Price: "2.80",
        FullPrice: "3.50",
    },
    {
        id: "55565",
        Name: "Tiramitsu Banofee",
        Category: "Dessert",
        UnderCategory: "Tiramitsu",
        Picture: "55565.jpeg",
        Description: "",
        Price: "2.80",
        FullPrice: "3.50",
    },
]
