export const teamDatas = [
    {
        id: "0001",
        Name: "Bruce Wayne",
        UserName: "Batman",
        ProfilePicture: "BruceWayne.png",
        Title: "Owner",
        Mail: "BruceWayne@cashier.com",
        Password: "p",
        Pin: "0000",
        StartDate: "01/03/2024",

    },
    {
        id: "0002",
        Name: "Alfred Pennyworth",
        UserName: "Alfred",
        ProfilePicture: "AlfredPennyworth.jpeg",
        Title: "Manager",
        Mail: "Alfred@cashier.com",
        Password: "p",
        Pin: "0000",
        StartDate: "01/03/2024",
    },
    {
        id: "0003",
        Name: "Young Robin",
        UserName: "Robin",
        ProfilePicture: "YoungRobin.png",
        Title: "Employee",
        Mail: "Robin@cashier.com",
        Password: "p",
        Pin: "0000",
        StartDate: "01/03/2024",
    },
    {
        id: "0004",
        Name: "Kitty Cat",
        UserName: "Catwoman",
        ProfilePicture: "KittyCat.jpeg",
        Title: "Owner",
        Mail: "Catwoman@cashier.com",
        Password: "p",
        Pin: "0000",
        StartDate: "01/03/2024",
    },
    {
        id: "0005",
        Name: "Dr Freezer",
        UserName: "Freezer",
        ProfilePicture: "DrFreezer.jpeg",
        Title: "Employee",
        Mail: "Freezer@cashier.com",
        Password: "p",
        Pin: "0000",
        StartDate: "01/03/2024",
    },
    {
        id: "0006",
        Name: "Le Joker",
        UserName: "Joker",
        ProfilePicture: "LeJoker.jpeg",
        Title: "Employee",
        Mail: "Joker@cashier.com",
        Password: "p",
        Pin: "0000",
        StartDate: "01/03/2024",
    },
    {
        id: "0007",
        Name: "William",
        UserName: "Le boufon vert",
        ProfilePicture: "William.jpeg",
        Title: "employee",
        Mail: "Boufon@cashier.com",
        Password: "p",
        Pin: "0000",
        StartDate: "01/03/2024",
    },
    {
        id: "0008",
        Name: "Marshal Matters",
        UserName: "Eminem",
        ProfilePicture: "MarshalMatters.jpeg",
        Title: "Manager",
        Mail: "Eminem@cashier.com",
        Password: "p",
        Pin: "0000",
        StartDate: "01/03/2024",
    },
    {
        id: "0009",
        Name: "Aubrey Graham",
        UserName: "Drake",
        ProfilePicture: "AubreyGraham.jpeg",
        Title: "Manager",
        Mail: "Drake@cashier.com",
        Password: "p",
        Pin: "0000",
        StartDate: "01/03/2024",
    },
    {
        id: "00010",
        Name: "Nessim Kouachi",
        UserName: "Nessim",
        ProfilePicture: "NessimKouachi.png",
        Title: "Central",
        Mail: "BruceWayne@cashier.com",
        Password: "p",
        Pin: "0000",
        StartDate: "01/03/2024",
    },
]
